### ISSUE TITLE
Resnet layers

### ISSUE THREAD

**Issue by AdityaNikhil** [MaheepChaudhary/Stand-Alone_Self-Attention#1]
This is one of the most elegant implementations of this paper. 🎉🎉
I am glad I came across this repository. 🎈

I just have few **questions** about the implementation and the paper.

1) Can you give a brief about the attention implementations. I don't understand the difference between the two attention mechanisms. Not the paper nor the implementation.

2) I think your implementation only runs **Resnet50** right? I mean, I didn't count the layers individually but there seem like many layers. I think it'll be great if you add functionality to select the number of layers(resnet26, 38, 50) to run on like in the paper.

3) About the paper,
Can you explain this statement in the paper,

> To bridge the gap between convolutions and self-attention while not significantly increasing computation, distance-based 
> information is introduced in the pointwise 1 × 1 convolution (WV) through spatially-varying linear transformations.

I am actually a research intern and working on vision transformers. This is a great headstart for me following your simple codes. 
Hope to see more such implementations! 😄

**Comment by MaheepChaudhary** [comment]
Thank you for appreciating the implementation. There are 2 types of attentions that has been proposed in the paper i.e. 
1. Difference between attentions: -
> This type of attention was introduced as the normal attention, used under perform the CNN in it;s initial layers i.e. the normal attention is not able to extract the broad features such as edges, shapes etc. but it was performing comparably CNN in later layers which focused on extracting minute features in the image. Therefore they introduced the attention stem which was used to extract the broad features and was performing comparably to CNN in initial layers. 
> The math part of the attention stem is introduced in the appendix, I hope it will give you some of the insights. 

2. I will try to include the option asap. In the meantime if you want to try your hands on it to include the feature you are most welcomed :see_no_evil: 

3. " To bridge the gap between convolutions and self-attention while not significantly increasing computation, distance-based
information is introduced in the point wise 1 × 1 convolution (WV) through spatially-varying linear transformations."
> They authors are trying to explain how the different location in image are not only encoded based on their pixel value but also on their location which is achieved by passing the image into a 1*1 kernel. As in the blog of ![jayalmamar](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiSu8SPh_3wAhU5yzgGHSo5BEcQFjACegQIAxAD&url=https%3A%2F%2Fjalammar.github.io%2Fillustrated-transformer%2F&usg=AOvVaw3WDsJY95mEQ_Dau-V15P8w) you can see the position of words in the sentence play an important role similarly the location of pixels also plays in attention

**Comment by AdityaNikhil** [comment]
Thank you..!✨
**About the first question**, I did see the appendix. I re-read it several times. I am unable to understand especially this part,

![image](https://user-images.githubusercontent.com/30192967/120747411-95550580-c51e-11eb-9f59-4273b16ce2b2.png)

And **about the functionality** to select layers, I'll see what I can do.!✌
